const SET_COLLECTION = 'SET_COLLECTION';
const ADD_TRACK = 'ADD_TRACK';
const DELETE_TRACK = 'DELETE_TRACK';
const SORT_COLLECTION = 'SORT_COLLECTION';
const FILTER_COLLECTION = 'FILTER_COLLECTION';

export {
    SET_COLLECTION,
    ADD_TRACK,
    DELETE_TRACK,
    SORT_COLLECTION,
    FILTER_COLLECTION
};
