const SET_ID = 'SET_ID';
const SET_TRACK = 'SET_TRACK';
const SET_LIST = 'SET_LIST';
const SET_PLAYBACK = 'SET_PLAYBACK';
const SET_DURATION = 'SET_DURATION';
const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
const SET_VOLUME = 'SET_VOLUME';
const SET_REPEATABLE = 'SET_REPEATABLE';
const SET_ADDED = 'SET_ADDED';
const INCREMENT_CURRENT_TIME = 'INCREMENT_CURRENT_TIME';

export {
    SET_ID,
    SET_TRACK,
    SET_LIST,
    SET_PLAYBACK,
    SET_DURATION,
    SET_CURRENT_TIME,
    SET_VOLUME,
    INCREMENT_CURRENT_TIME,
    SET_REPEATABLE,
    SET_ADDED
};